# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auther_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther_img', models.CharField(max_length=120)),
                ('auther_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Auther')),
            ],
        ),
    ]
