# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auther_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auther_books',
            name='auther_books',
        ),
        migrations.DeleteModel(
            name='Auther_books',
        ),
    ]
