# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180330_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther_name', models.CharField(max_length=120)),
                ('auther_img', models.CharField(max_length=1200)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Books')),
            ],
        ),
    ]
