# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auther',
            name='auther_img',
            field=models.FileField(upload_to=''),
        ),
    ]
