# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180330_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auther',
            name='auther',
        ),
        migrations.DeleteModel(
            name='Auther',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
