# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0007_auto_20180330_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther_name', models.CharField(max_length=120)),
                ('auther_book_price', models.CharField(max_length=1500)),
                ('auther_img', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='auther',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Books'),
        ),
    ]
